# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mike Perrenoud
email: info@consultwithmike.us
description: > # this means to ignore newlines until "baseurl:"
  Mike Perrenoud is a 15 year veteran developer, polyglot, mentor,
  and all around nice guy. He enjoys helping people and making a
  difference in their lives.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://trainwithmike.us" # the base hostname & protocol for your site
twitter_username: consultwmike
github_username:  mperrenoud
gems:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from

# Build settings
markdown: kramdown
